version: '3.8'
name: "done_trans"
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - leet_network
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      args:
        - IP_HOST=${IP_HOST}
        - FRONTPORT=${FRONTPORT}
    ports:
      - ${FRONTPORT}:${FRONTPORT}
    networks:
      - leet_network
    #volumes:
      #- ./frontend:/app
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      #dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    networks:
      - leet_network
    volumes:
      - ./backend/src:/app/src
      - ./backend/uploads:/app/uploads
    env_file:
      - ./.env
    depends_on:
      - db
      - migration
    restart: unless-stopped
  migration:
    build:
      context: ./backend/prisma
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - leet_network
    depends_on:
      - db

networks:
  leet_network:
volumes: 
  db:
#